try:
    number1 = 10
    number2 = 0
    result = number1 // number2
    print(result)
except Exception as e:
    print(f"Exception was thrown: {e}")
